version: 2
executorType: docker
containerInfo:
    cmd: ["/bin/bash"]
  - image: jasonlaster11/moz-mc:latest
    env:
      - DISPLAY=unix:99
      - SHELL=/bin/bash
stages:
  build:
    workDir: ~/debugger
    steps:
      - type: checkout

      - type: shell
        name: Copy Config Files
        shell: /bin/bash --login
        command: cp configs/ci.json configs/local.json

      - type: shell
        name: Yarn Install
        shell: /bin/bash --login
        command: yarn

      - type: shell
        name: Yarn Lint
        shell: /bin/bash --login
        command: |
            set -exu
            yarn lint-css
            yarn lint-js
            yarn lint-md

      - type: shell
        name: Flow
        shell: /bin/bash --login
        command: |
            set -exu
            yarn flow
        environment:
          TERM: dumb

      - type: shell
        name: Yarn Check yarn.lock
        shell: /bin/bash --login
        command: |
            set -exu
            yarn check

      - type: shell
        name: Node Unit Tests
        shell: /bin/bash --login
        command: |
            set -exu
            yarn test

      - type: shell
        name: Mochitests
        shell: /bin/bash --login
        command: |
            node ./bin/run-mochitests
