/* eslint max-nested-callbacks: ["error", 6] */

import {
  simplifyDisplayName,
  formatDisplayName,
  formatCopyName,
  getLibraryFromUrl,
  collapseFrames
} from "../frame";

const cases = {
  defaultCase: [["define", "define"]],

  objectProperty: [
    ["z.foz", "foz"],
    ["z.foz/baz", "baz"],
    ["z.foz/baz/y.bay", "bay"],
    ["outer/x.fox.bax.nx", "nx"],
    ["outer/fow.baw", "baw"],
    ["fromYUI._attach", "_attach"],
    ["Y.ClassNameManager</getClassName", "getClassName"],
    ["orion.textview.TextView</addHandler", "addHandler"],
    ["this.eventPool_.createObject", "createObject"]
  ],

  arrayProperty: [
    ["this.eventPool_[createObject]", "createObject"],
    ["jQuery.each(^)/jQuery.fn[o]", "o"],
    ["viewport[get+D]", "get+D"],
    ["arr[0]", "0"]
  ],

  functionProperty: [
    ["fromYUI._attach/<.", "_attach"],
    ["Y.ClassNameManager<", "ClassNameManager"],
    ["fromExtJS.setVisible/cb<", "cb"],
    ["fromDojo.registerWin/<", "registerWin"]
  ],

  annonymousProperty: [["jQuery.each(^)", "each"]]
};

describe("function names", () => {
  describe("simplifying display names", () => {
    Object.keys(cases).forEach(type => {
      cases[type].forEach(([kase, expected]) => {
        it(`${type} - ${kase}`, () =>
          expect(simplifyDisplayName(kase)).toEqual(expected));
      });
    });
  });

  describe("formatting display names", () => {
    it("uses a library description", () => {
      const frame = {
        library: "Backbone",
        displayName: "extend/child",
        source: {
          url: "assets/backbone.js"
        }
      };

      expect(formatDisplayName(frame)).toEqual("Create Class");
    });

    it("shortens an anonymous function", () => {
      const frame = {
        displayName: "extend/child/bar/baz",
        source: {
          url: "assets/bar.js"
        }
      };

      expect(formatDisplayName(frame)).toEqual("baz");
    });

    it("truncates long function names", () => {
      const frame = {
        displayName: "bazbazbazbazbazbazbazbazbazbazbazbazbaz",
        source: {
          url: "assets/bar.js"
        }
      };

      expect(formatDisplayName(frame)).toEqual("...zbazbazbazbazbazbazbazbaz");
    });
  });

  describe("formatCopyName", () => {
    it("simple", () => {
      const frame = {
        displayName: "child",
        location: {
          line: 12
        },
        source: {
          url: "todo-view.js"
        }
      };

      expect(formatCopyName(frame)).toEqual("child (todo-view.js#12)");
    });
  });

  describe("getLibraryFromUrl", () => {
    describe("When Preact is on the frame", () => {
      it("should return Preact and not React", () => {
        const frame = {
          displayName: "name",
          location: {
            line: 12
          },
          source: {
            url: "https://cdnjs.cloudflare.com/ajax/libs/preact/8.2.5/preact.js"
          }
        };

        expect(getLibraryFromUrl(frame)).toEqual("Preact");
      });
    });
  });

  describe("collapseFrames", () => {
    it("collapses React component render frames and Webpack bootstrap frames", () => {
      const frames = [
        {
          id: "0",
          displayName: "render",
          source: {
            url: "webpack:///src/App.js"
          }
        },
        {
          id: "1",
          displayName:
            "_renderValidatedComponentWithoutOwnerOrContext/renderedElement<",
          library: "React",
          source: {
            url: "webpack:///~/react-dom/lib/ReactCompositeComponent.js"
          }
        },
        {
          id: "2",
          displayName: "render",
          library: "React",
          source: {
            url: "webpack:///~/react-dom/lib/ReactMount.js"
          }
        },
        {
          id: "3",
          displayName: "__webpack_require__",
          library: "Webpack",
          source: {
            url: "webpack:///webpack/bootstrap 01d88449ca6e9335a66f"
          }
        },
        {
          id: "4",
          displayName: "(global)",
          source: {
            url: "https://foobar.com/bundle.js"
          }
        }
      ];
      const collapsedFrames = collapseFrames(frames);

      expect(collapsedFrames).toEqual([
        frames[0],
        [frames[1], frames[2]],
        [frames[3], frames[4]]
      ]);
    });
  });

  it("groups async frames generated by Babel", () => {
    const frames = [
      {
        id: "0",
        displayName: "_callee2$",
        source: {
          url: "webpack:///entry.js"
        }
      },
      {
        id: "1",
        displayName: "tryCatch",
        source: {
          url:
            "webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/regenerator-runtime/runtime.js"
        }
      },
      {
        id: "2",
        displayName: "invoke",
        source: {
          url:
            "webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/regenerator-runtime/runtime.js"
        }
      },
      {
        id: "3",
        displayName: "defineIteratorMethods/</prototype[method]",
        source: {
          url:
            "webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/regenerator-runtime/runtime.js"
        }
      },
      {
        id: "4",
        displayName: "step",
        source: {
          url:
            "http://firefox-dev.tools/debugger-examples/examples/babel/bundle.js"
        }
      },
      {
        id: "5",
        displayName: "_asyncToGenerator/</<",
        source: {
          url:
            "http://firefox-dev.tools/debugger-examples/examples/babel/bundle.js"
        }
      },
      {
        id: "6",
        displayName: "Promise",
        source: {
          url:
            "webpack:///Users/jlaster/src/mozilla/debugger-examples/node_modules/core-js/modules/es6.promise.js"
        }
      },
      {
        id: "7",
        displayName: "_asyncToGenerator/<",
        source: {
          url:
            "http://firefox-dev.tools/debugger-examples/examples/babel/bundle.js"
        }
      },
      {
        id: "8",
        displayName: "onclick",
        source: {
          url: "http://firefox-dev.tools/debugger-examples/examples/babel/"
        }
      }
    ];
    const collapsedFrames = collapseFrames(frames);

    expect(collapsedFrames).toEqual([frames[0], frames.slice(1, 7), frames[7]]);
  });
});
