module.exports = {
  asm: require("./asm"),
  breaking: require("./breaking"),
  breakpoints: require("./breakpoints"),
  breakpointsCond: require("./breakpoints-cond"),
  callStack: require("./call-stack"),
  expressions: require("./expressions"),
  debuggerButtons: require("./debugger-buttons"),
  editorSelect: require("./editor-select"),
  editorPreview: require("./editor-preview"),
  editorGutter: require("./editor-gutter"),
  editorHighlight: require("./editor-highlight"),
  keyboardNavigation: require("./keyboard-navigation"),
  keyboardShortcuts: require("./keyboard-shortcuts"),
  iframes: require("./iframes"),
  navigation: require("./navigation"),
  pauseOnExceptions: require("./pause-exceptions"),
  prettyPrint: require("./pretty-print"),
  prettyPrintPaused: require("./pretty-print-paused"),
  returnvalues: require("./returnvalues"),
  scopes: require("./scopes"),
  searching: require("./searching"),
  sources: require("./sources"),
  sourceMaps: require("./sourcemaps"),
  sourceMaps2: require("./sourcemaps2"),
  sourceMapsBogus: require("./sourcemaps-bogus")
};
