// @flow

/* -*- indent-tabs-mode: nil; js-indent-level: 2 -*- */
/* vim: set ft=javascript ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

exports.UPDATE_EVENT_BREAKPOINTS = "UPDATE_EVENT_BREAKPOINTS";
exports.FETCH_EVENT_LISTENERS = "FETCH_EVENT_LISTENERS";

exports.TOGGLE_PRETTY_PRINT = "TOGGLE_PRETTY_PRINT";
exports.BLACKBOX = "BLACKBOX";

exports.ADD_BREAKPOINT = "ADD_BREAKPOINT";
exports.REMOVE_BREAKPOINT = "REMOVE_BREAKPOINT";
exports.ENABLE_BREAKPOINT = "ENABLE_BREAKPOINT";
exports.DISABLE_BREAKPOINT = "DISABLE_BREAKPOINT";
exports.SET_BREAKPOINT_CONDITION = "SET_BREAKPOINT_CONDITION";
exports.TOGGLE_BREAKPOINTS = "TOGGLE_BREAKPOINTS";

exports.ADD_SOURCE = "ADD_SOURCE";
exports.ADD_SOURCES = "ADD_SOURCES";
exports.LOAD_SOURCE_TEXT = "LOAD_SOURCE_TEXT";
exports.SELECT_SOURCE = "SELECT_SOURCE";
exports.SELECT_SOURCE_URL = "SELECT_SOURCE_URL";
exports.CLOSE_TAB = "CLOSE_TAB";
exports.CLOSE_TABS = "CLOSE_TABS";
exports.NAVIGATE = "NAVIGATE";
exports.RELOAD = "RELOAD";

exports.ADD_TABS = "ADD_TABS";
exports.SELECT_TAB = "SELECT_TAB";

exports.BREAK_ON_NEXT = "BREAK_ON_NEXT";
exports.RESUME = "RESUME";
exports.PAUSED = "PAUSED";
exports.PAUSE_ON_EXCEPTIONS = "PAUSE_ON_EXCEPTIONS";
exports.COMMAND = "COMMAND";
exports.SELECT_FRAME = "SELECT_FRAME";
exports.LOAD_OBJECT_PROPERTIES = "LOAD_OBJECT_PROPERTIES";
exports.ADD_EXPRESSION = "ADD_EXPRESSION";
exports.EVALUATE_EXPRESSION = "EVALUATE_EXPRESSION";
exports.UPDATE_EXPRESSION = "UPDATE_EXPRESSION";
exports.DELETE_EXPRESSION = "DELETE_EXPRESSION";

exports.RECORD_COVERAGE = "RECORD_COVERAGE";

exports.TOGGLE_FILE_SEARCH = "TOGGLE_FILE_SEARCH";
exports.SHOW_SOURCE = "SHOW_SOURCE";
