// @flow

/* -*- indent-tabs-mode: nil; js-indent-level: 2 -*- */
/* vim: set ft=javascript ts=2 et sw=2 tw=80: */
/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

export default {
  UPDATE_EVENT_BREAKPOINTS: "UPDATE_EVENT_BREAKPOINTS",
  FETCH_EVENT_LISTENERS: "FETCH_EVENT_LISTENERS",

  TOGGLE_PRETTY_PRINT: "TOGGLE_PRETTY_PRINT",
  BLACKBOX: "BLACKBOX",

  ADD_BREAKPOINT: "ADD_BREAKPOINT",
  REMOVE_BREAKPOINT: "REMOVE_BREAKPOINT",
  ENABLE_BREAKPOINT: "ENABLE_BREAKPOINT",
  DISABLE_BREAKPOINT: "DISABLE_BREAKPOINT",
  SET_BREAKPOINT_CONDITION: "SET_BREAKPOINT_CONDITION",
  TOGGLE_BREAKPOINTS: "TOGGLE_BREAKPOINTS",

  ADD_SOURCE: "ADD_SOURCE",
  ADD_SOURCES: "ADD_SOURCES",
  LOAD_SOURCE_TEXT: "LOAD_SOURCE_TEXT",
  SELECT_SOURCE: "SELECT_SOURCE",
  SELECT_SOURCE_URL: "SELECT_SOURCE_URL",
  HIGHLIGHT_LINES: "HIGHLIGHT_LINES",
  CLEAR_HIGHLIGHT_LINES: "CLEAR_HIGHLIGHT_LINES",
  CLOSE_TAB: "CLOSE_TAB",
  CLOSE_TABS: "CLOSE_TABS",
  NAVIGATE: "NAVIGATE",
  RELOAD: "RELOAD",

  ADD_TABS: "ADD_TABS",
  SELECT_TAB: "SELECT_TAB",

  BREAK_ON_NEXT: "BREAK_ON_NEXT",
  RESUME: "RESUME",
  PAUSED: "PAUSED",
  PAUSE_ON_EXCEPTIONS: "PAUSE_ON_EXCEPTIONS",
  COMMAND: "COMMAND",
  SELECT_FRAME: "SELECT_FRAME",
  LOAD_OBJECT_PROPERTIES: "LOAD_OBJECT_PROPERTIES",
  ADD_EXPRESSION: "ADD_EXPRESSION",
  EVALUATE_EXPRESSION: "EVALUATE_EXPRESSION",
  UPDATE_EXPRESSION: "UPDATE_EXPRESSION",
  DELETE_EXPRESSION: "DELETE_EXPRESSION",

  RECORD_COVERAGE: "RECORD_COVERAGE",

  TOGGLE_PROJECT_SEARCH: "TOGGLE_PROJECT_SEARCH",
  TOGGLE_FILE_SEARCH: "TOGGLE_FILE_SEARCH",
  TOGGLE_SYMBOL_SEARCH: "TOGGLE_SYMBOL_SEARCH",
  TOGGLE_FRAMEWORK_GROUPING: "TOGGLE_FRAMEWORK_GROUPING",
  SET_SYMBOL_SEARCH_TYPE: "SET_SYMBOL_SEARCH_TYPE",
  UPDATE_FILE_SEARCH_QUERY: "UPDATE_FILE_SEARCH_QUERY",
  TOGGLE_FILE_SEARCH_MODIFIER: "TOGGLE_FILE_SEARCH_MODIFIER",
  SHOW_SOURCE: "SHOW_SOURCE",
  TOGGLE_PANE: "TOGGLE_PANE"
};
